### ISSUE TITLE
Option to specify Jira epic (or task) for further task (or subtask) creation

### ISSUE THREAD

**Issue by mildas** [RedHatQE/newa#106]
Currently, if an user wants NEWA to use already existing epic and let it add tasks there, the only option is to define identier in config:
```
issues:
  - ...
    newa_id: "XYZ#{{ ERRATUM.id }}"
```
and add the identifier (`::: NEWA XYZ#123`) to epic description.

It would be simpler to have an option in CLI to choose which epic should be used rather then have specific identifier and need to edit epic description.

**Comment by kkaarreell** [comment]
Given it won't be NEWA finding the issue but a user telling issue ID, we need to make sure NEWA would find it in subsequent invocations and except updating newa ID (which should be already in the code) we need to also add NEWA label.

**Comment by kkaarreell** [comment]
WIP in https://github.com/RedHatQE/newa/pull/117

**Comment by kkaarreell** [comment]
Merged.
Another related MR https://github.com/RedHatQE/newa/pull/118
