### ISSUE TITLE
report should update ticket states (opt-in) as well

### ISSUE THREAD

**Issue by lukaszachy** [RedHatQE/newa#121]
In 'report' newa is able to update jira ticket with link to the report portal and short summary.

It would be great if there is a way to automatically update the state as well. 
IMO there could be more options as one possible scenario is:
- all results Green -> status done
- some results 'to intvestigate' -> status 'in progress' 
'

**Comment by kkaarreell** [comment]
I see two options here:
1. We could extend the Jira project related settings in the issue-config file to include the respective state settings like `success: Done` and `failure: in_progress` and then in the Jira issue action definition enable such automation transitions.
2. Leave state settings only on the Jira issue action definition where user could choose any state they want. I don't like this solution as I like when the transition is defined only in the project settings at one place.

**Comment by kkaarreell** [comment]
An attempt to implement this is in https://github.com/RedHatQE/newa/pull/122
Please check/test.

**Comment by kkaarreell** [comment]
Implemented.
