### ISSUE TITLE
Test history in Report Portal

### ISSUE THREAD

**Issue by brakogh** [RedHatQE/newa#143]
Test case history in RP is broken when "Parameters" in "Item Details" tab of the tests results [1] differs. In tier testing we are removing this parameters to preserve test history. Would it be possible to do the same for newa?

https://reportportal-rhel.apps.ocp-c1.prod.psi.redhat.com/ui/#baseosqe/launches/all/11723/615074/615075/log

**Comment by kkaarreell** [comment]
Hi @brakogh , how and when do you clear it? Can you paste an example? Maybe TMT/reportportal plugin should be told to not set it (or clear it). WDYT?

**Comment by kkaarreell** [comment]
Looking at the example, would it be sufficient just to not set `TESTING_FARM_REQUEST_ID`?

**Comment by brakogh** [comment]
I'm using [1] with $RP_EXCLUDE_VARIABLES defined as [2]. So you can tell RP plugin to exclude those. I'm clearing all of those as those are TF parameters, not test parameters.

1. https://gitlab.cee.redhat.com/baseos-qe/tier-automation/-/blob/tmt/tiers.sh#L149
2. https://gitlab.cee.redhat.com/baseos-qe/tier-automation/-/blob/tmt/tiers.sh#L14

**Comment by kkaarreell** [comment]
Right. The reason I was asking is whether parameters like `TESTING_FARM_GIT_REF, TESTING_FARM_GIT_URL, TESTING_FARM_TEST_TYPE` are really a problem. I mean, if I am running a test from a different repo or branch, maybe it is not the "same" test any longer and test case history is not relevant. But maybe the potential benefit is not worth the issues and better clear them all. I will try to make it configurable.

**Comment by kkaarreell** [comment]
@brakogh  Btw, would you have more details about the issue? Is there some tracker for it? I am confused because one of those parameters is TF request uuid which will clearly differ for each test iteration and yet I can see case history for my tests.

**Comment by brakogh** [comment]
RP documentation for the reference [1]. If tests metadata contains "test case id", parameters are ignored. If test case ID is missing, RP generates one using reference and tests parameters.
1. https://reportportal.io/docs/work-with-reports/TestCaseId

**Comment by kkaarreell** [comment]
Filtering test parameters may be a workaround to some extent. This feature is being worked on in https://github.com/RedHatQE/newa/pull/146.
