### ISSUE TITLE
newa user config file

### ISSUE THREAD

**Issue by kkaarreell** [RedHatQE/newa#22]
Users should be able to define all important variables (like ET URL, Jira token,...) in a config file, for example `~/.newa/config`
At the same time, each such config option should be also configurable through environment variable having `NEWA_` prefix to simplify integration into pipelines.

**Comment by kkaarreell** [comment]
I tried to approach this in https://github.com/RedHatQE/newa/pull/30

**Comment by The-Mule** [comment]
@kkaarreell I think we might want to reconsider having `jira_project` in the newa config. The thing is that project is a kind of component-specific thing. Different teams will want to use their own projects for their components. Hence I believe this particular config fits better in to component configuration (as implemented in #20 ).

**Comment by kkaarreell** [comment]
i think that it might be handy to be able to specify it at multiple levels (envvar, newa config, jira subcommand option, issue config) with defined (hardcoded) priorities. Also, partially related problem is splitting issue config into multiple files.

**Comment by kkaarreell** [comment]
https://github.com/RedHatQE/newa/pull/30 got merged.
