### ISSUE TITLE
Create a project skeleton

### ISSUE THREAD

**Issue by thrix** [RedHatQE/newa#5]
The command line synopsis of the tool will be:

```
newa event --errata 12345 jira schedule execute report
newa event jira --yaml errata-12345 schedule execute report
```

The command will be able to 

Each command will read and output a yaml file, that will 

@ksrot @happz pls edit and revisit :)

**Comment by thrix** [comment]
@happz @kkaarreell I assume we can close this?

**Comment by kkaarreell** [comment]
I believe so.

**Comment by thrix** [comment]
Closing
